---
PreCommit:

  ALL:
    problem_on_unmodified_line: warn

  PerlCritic:
    enabled: true
    required_executable: perlcritic
    flags: [--verbose, '1', --quiet]
    include:
      - "**/*.pl"

  Cppcheck:
    description: Lint C/C++ source files with cppcheck
    enabled: true
    required_executable: cppcheck
    flags:
      - --quiet
      - --std=c++11
      - --enable=all
      - --language=c++
      - --inline-suppr
      - --suppress=missingIncludeSystem
      - "--template={file}:{line}:{message}"
    include:
      - '**/*.cpp'
      - '**/*.h'

  TrailingWhitespace:
    enabled: true

  FileEncoding:
    description: Check text files are valid UTF-8
    enabled: true

  SingleNewlineAtEof:
    description: Check text files end with a single newline
    enabled: true

  Copyright:
    description: Check copyright notices are present and updated
    enabled: true

  YamlLint:
    enabled: true
    on_warn: fail
